spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/bank_db
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
  main:
    banner-mode: off